use single config file for all deployment scripts

diff --git a/site/profiles/files/Debian/config/8/reapply b/site/profiles/files/Debian/config/8/reapply
--- a/site/profiles/files/Debian/config/8/reapply
+++ b/site/profiles/files/Debian/config/8/reapply
@@ -1,17 +1,18 @@
 #!/bin/bash
 
-export SEMESTER="Spring2017"
-export BRANCH="master"
-export BUILD="1"
-export LIBSYNC="http://duplicon.nmt.edu/preseed/jessie/libsync"
-export WPCONF="http://duplicon.nmt.edu/preseed/jessie/winpuppet.conf"
-export SYNCPRE="http://template.nmt.edu/images/Spring2017"
+if [ -e "/usr/local/etc/template.conf"]
+	. /usr/local/etc/template.conf
+else
+	printf "Could not read deployment configuration!\n"
+	exit 66 # EX_NOINPUT from sysexits.h
+fi
+
 export UNATTEND="/media/winpart/Windows/Panther/unattend.xml"
 export WPCONFDIR="/media/winpart/ProgramData/PuppetLabs/puppet/etc"
 
 download_libsync() {
 
-	wget -P /tmp $LIBSYNC > /dev/null 2>&1
+	wget -P /tmp $PRESEED/libsync > /dev/null 2>&1
 	if [ -s "/tmp/libsync" ]
 	then
 		return
@@ -24,7 +25,7 @@ download_libsync() {
 
 download_wpconf() {
 
-	wget -P /tmp $WPCONF > /dev/null 2>&1
+	wget -P /tmp $PRESEED/winpuppet.conf > /dev/null 2>&1
 	if [ -s "/tmp/winpuppet.conf" ]
 	then
 		return
diff --git a/site/profiles/files/Debian/config/8/remote_reapply b/site/profiles/files/Debian/config/8/remote_reapply
--- a/site/profiles/files/Debian/config/8/remote_reapply
+++ b/site/profiles/files/Debian/config/8/remote_reapply
@@ -1,7 +1,13 @@
 #!/bin/bash
 
+if [ -e "/usr/local/etc/template.conf"]
+	. /usr/local/etc/template.conf
+else
+	printf "Could not read deployment configuration!\n"
+	exit 66 # EX_NOINPUT from sysexits.h
+fi
+
 export ME="$(hostname -s)"
-export RELEASE="Spring2017-master.1"
 export DATA="/var/lib/transmission-daemon/downloads"
 
 winpart=$(/sbin/blkid -o device -t TYPE=ntfs)
@@ -14,11 +20,11 @@ date1="$(date)"
 
 res1="null"
 res2="null"
-if [ -d "$DATA/$RELEASE" ]
+if [ -d "$DATA/$TEMPLATE" ]
 then
-	cat $DATA/$RELEASE/$RELEASE.vhd1 | dd of=/dev/sda1 bs=64k > /dev/null 2>&1
+	cat $DATA/$TEMPLATE/$TEMPLATE.vhd1 | dd of=/dev/sda1 bs=64k > /dev/null 2>&1
 	res1=$?
-	pbzip2 -c -d $DATA/$RELEASE/$RELEASE.vhd2.bz2 | dd of=/dev/sda2 bs=4M > /dev/null 2>&1
+	pbzip2 -c -d $DATA/$TEMPLATE/$TEMPLATE.vhd2.bz2 | dd of=/dev/sda2 bs=4M > /dev/null 2>&1
 	res2=$?
 fi
 
@@ -26,4 +32,4 @@ fi
 
 date2="$(date)"
 
-printf "I completed the template application process with $RELEASE.\n\n * Started at: $date1\n * Finished at: $date2\n\n * NTFS boot partition return code was: $res1\n * NTFS main partition return code was: $res2\n\nDon't forget to clean my old Puppet certificates!\n\nSincerely,\n$ME" | mail -r "$ME@nmt.edu" -s "$ME reapply" itc-triage@nmt.edu
+printf "I completed the template application process with $TEMPLATE.\n\n * Started at: $date1\n * Finished at: $date2\n\n * NTFS boot partition return code was: $res1\n * NTFS main partition return code was: $res2\n\nDon't forget to clean my old Puppet certificates!\n\nSincerely,\n$ME" | mail -r "$ME@nmt.edu" -s "$ME reapply" itc-triage@nmt.edu
diff --git a/site/profiles/files/Debian/config/8/reseed b/site/profiles/files/Debian/config/8/reseed
--- a/site/profiles/files/Debian/config/8/reseed
+++ b/site/profiles/files/Debian/config/8/reseed
@@ -1,17 +1,17 @@
 #!/bin/bash
 
-export SEMESTER="Spring2017"
-export BRANCH="master"
-export BUILD="1"
-export LIBSYNC="http://duplicon.nmt.edu/preseed/jessie/libsync"
-export SYNCPRE="http://template.nmt.edu/images/Spring2017"
-export BTHASH="c51a49547a5122c8f73c322b63fdf4c851f2ff05"
-export OLDBTHASHES="65d0a33272f8de9effa8ab9adf77ca107659d14a 6b10051ff0fd733544fae8e2ebce4d55ce733ece"
+if [ -e "/usr/local/etc/template.conf"]
+	. /usr/local/etc/template.conf
+else
+	printf "Could not read deployment configuration!\n"
+	exit 66 # EX_NOINPUT from sysexits.h
+fi
+
 export WINMODE="Post"
 
 download_libsync() {
 
-    wget -P /tmp $LIBSYNC > /dev/null 2>&1
+    wget -P /tmp $PRESEED/libsync > /dev/null 2>&1
     if [ -s "/tmp/libsync" ]
     then
         return
@@ -24,12 +24,7 @@ download_libsync() {
 download_libsync
 source /tmp/libsync
 start_transmission
-for hash in $OLDBTHASHES
-do
-    transmission-remote -t $hash --remove-and-delete
-    sleep 2
-done
-transmission-remote -t $BTHASH --remove
+transmission-remote -t $TORRENT --remove
 sleep 2
 torrent_image
 rm -f /tmp/libsync
